### ISSUE TITLE
Adaptation options / qualities

### ISSUE THREAD

**Issue by fkgl** [sarpreetsingh3131/4dv50e#1]
Hello, 
Please I have the following questions:
What is the format of the adaptation options used?

What is the formula (equation) used to determine latency and packet loss?

Best regards.

**Comment by sarpreetsingh3131** [comment]
Hey,
Sorry for late reply. Do you mean the raw adaption data? Please tell me the name of the file.

**Comment by fkgl** [comment]
@sarpreetsingh3131 
Hi, 
In the file Feedback_loop.py  you have function composeAdaptationOption, this options what information contains (just the distribution or there is other) , are they the format tuples ?

Best regards.

**Comment by sarpreetsingh3131** [comment]
Hey, in FeedbackLoop.**java**, the newConfiguration parameter to the composeAdaptationOption method contains the power settings of each mote. Inside the method we adds the link distributions to the motes.

**Comment by fkgl** [comment]
@sarpreetsingh3131 
Thank you very much for the clarification.

**Comment by fkgl** [comment]
Hi,
Please, if it's possible to give me your personal email address

Best regards,
Fatma
